# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 00:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4, null=True)),
                ('player_league', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.CharField(max_length=3, null=True)),
                ('position', models.CharField(max_length=20, null=True)),
                ('height', models.CharField(max_length=3, null=True)),
                ('weight', models.CharField(max_length=3, null=True)),
                ('appearances', models.CharField(max_length=5, null=True)),
                ('goals', models.CharField(max_length=3, null=True)),
                ('assists', models.CharField(max_length=3, null=True)),
                ('yellow', models.CharField(max_length=3, null=True)),
                ('red', models.CharField(max_length=3, null=True)),
                ('shots_per_game', models.CharField(max_length=3, null=True)),
                ('ps', models.CharField(max_length=5, null=True)),
                ('aerials_won', models.CharField(max_length=5, null=True)),
                ('motm', models.CharField(max_length=3, null=True)),
                ('rating', models.CharField(max_length=10, null=True)),
                ('skills', models.CharField(max_length=20, null=True)),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('league', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['league', 'name'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='restapi.Team'),
        ),
    ]
