# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
    ]
