# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20160422_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
    ]
