# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20160414_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='restapi.Team'),
        ),
    ]
