# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20160422_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_league',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='teams', to='restapi.Player'),
        ),
    ]
